Repository nowwater/Reliable-Chatting-Platform, pull requests merged in 2021-05, with the labels that each got.

#122 stompClient Refactoring : not singleton, disposeAll, error handling, …
  client/app/src/main/java/com/example/chattingapp/adapter/MessagelistAdapter.kt
  client/app/src/main/java/com/example/chattingapp/adapter/RoomlistAdapter.kt
  client/app/src/main/java/com/example/chattingapp/service/EventApiService.kt
  client/app/src/main/java/com/example/chattingapp/service/MessageApiService.kt
  client/app/src/main/java/com/example/chattingapp/service/RoomApiService.kt
  client/app/src/main/java/com/example/chattingapp/service/util/stomp/MyStompClient.kt
  client/app/src/main/java/com/example/chattingapp/service/util/stomp/StompApiService.kt
  client/app/src/main/java/com/example/chattingapp/view/MessageChatActivity.kt
  client/app/src/main/java/com/example/chattingapp/view/fragment/MessagelistFragment.kt
  client/app/src/main/java/com/example/chattingapp/view/fragment/RoomlistFragment.kt
Labels: Android, Refactoring

#124 bug fix
  client/app/src/main/java/com/example/chattingapp/db/dao/MessageDao.kt
  client/app/src/main/java/com/example/chattingapp/db/dao/RoomDao.kt
  client/app/src/main/java/com/example/chattingapp/view/MessageChatActivity.kt
Labels: Android, bug

#125 fix : double message problem in chatting room
  client/app/src/main/java/com/example/chattingapp/view/fragment/MessagelistFragment.kt
Labels: Android, Kotlin, xml

#128 feat: add message nodejs server
  message/config/db.js
  message/index.js
  message/package-lock.json
  message/package.json
  message/routes/routes.js
Labels: Establish, Node.js

#129 fix: db connection
  message/config/db.js
Labels: Node.js, bug

#152 fix:signin check
  client/app/src/main/java/com/example/chattingapp/dto/request/LoginRequest.kt
  client/app/src/main/java/com/example/chattingapp/service/util/rest/RestApiServiceGenerator.kt
  client/app/src/main/java/com/example/chattingapp/view/LoginActivity.kt
  client/app/src/main/java/com/example/chattingapp/view/SignUpActivity.kt
Labels: Android, Kotlin, xml

#155 feat: add profile image field in User
  server/src/main/java/com/Gongdae9/user/domain/User.java
Labels: Domain, Spring, enhancement

#158 feat: add updating user's profile image
  server/src/main/java/com/Gongdae9/user/api/UserApiController.java
  server/src/main/java/com/Gongdae9/user/domain/User.java
  server/src/main/java/com/Gongdae9/user/dto/UserDto.java
  server/src/main/java/com/Gongdae9/user/service/UserService.java
Labels: Domain, Spring, enhancement

#165 feat: add decoding base64 string data
  server/src/main/java/com/Gongdae9/user/service/UserService.java
  server/src/test/java/com/Gongdae9/ProfileUploadTest.java
Labels: Spring, bug, enhancement

#166 feat: add fcmToken in login service
  server/src/main/java/com/Gongdae9/user/domain/User.java
  server/src/main/java/com/Gongdae9/user/dto/LoginRequestDto.java
  server/src/main/java/com/Gongdae9/user/service/UserService.java
  server/src/test/java/com/Gongdae9/loginSessionTest.java
Labels: Spring, enhancement

#167 Feat/issue 161/push service
  client/app/build.gradle
  client/app/google-services.json
  client/app/src/main/AndroidManifest.xml
  client/app/src/main/java/com/example/chattingapp/MyFireBaseMessagingService.java
  client/app/src/main/java/com/example/chattingapp/view/LoginActivity.kt
  client/build.gradle
  server/build.gradle
  server/src/main/java/com/Gongdae9/fcm/FCMInitializer.java
  server/src/main/java/com/Gongdae9/fcm/api/FCMApiController.java
  server/src/main/java/com/Gongdae9/fcm/service/FCMService.java
  server/src/main/resources/reliablemessage-168d1-firebase-adminsdk-olyui-caec3e6e5f.json
Labels: Android, Spring, enhancement

#174 feat : signup
  client/app/src/main/java/com/example/chattingapp/view/LoginActivity.kt
  client/app/src/main/java/com/example/chattingapp/view/ProfileChangeActivity.kt
  client/app/src/main/java/com/example/chattingapp/view/SignUpActivity.kt
  client/app/src/main/res/layout/activity_signup.xml
Labels: Android, Kotlin, xml

#179 fix: updating FCM token when to login
  server/src/main/java/com/Gongdae9/user/service/UserService.java
Labels: Spring, bug

#182 feat: encoding user's password when to login
  server/build.gradle
  server/src/main/java/com/Gongdae9/security/SecurityConfig.java
  server/src/main/java/com/Gongdae9/user/api/UserApiController.java
  server/src/main/java/com/Gongdae9/user/service/UserService.java
Labels: Spring, enhancement

#187 fix: login matches() method
  server/src/main/java/com/Gongdae9/user/service/UserService.java
Labels: Spring, bug

#189 fix: changed command from compile to implementation
  server/build.gradle
  server/src/main/java/com/Gongdae9/DemoApplication.java
Labels: Spring, bug

#203 Feat/issue 161/push service
  server/src/main/java/com/Gongdae9/fcm/api/FCMApiController.java
  server/src/main/java/com/Gongdae9/friend/api/FriendApiController.java
  server/src/main/java/com/Gongdae9/message/controller/MessageController.java
  server/src/main/java/com/Gongdae9/room/api/RoomApiContoller.java
  server/src/main/java/com/Gongdae9/room/service/RoomService.java
  server/src/main/java/com/Gongdae9/user/repository/UserRepository.java
  server/src/main/resources/reliablemessage-168d1-firebase-adminsdk-olyui-caec3e6e5f.json
Labels: Spring, enhancement
