Repository nowwater/Reliable-Chatting-Platform, pull requests merged in 2021-04, with the labels that each got.

#8 feat: add User,Room,JoinRoom
  server/src/main/java/com/Gongdae9/domain/JoinRoom.java
  server/src/main/java/com/Gongdae9/domain/Room.java
  server/src/main/java/com/Gongdae9/domain/User.java
Labels: Domain, enhancement

#14 feat: complete domain
  server/src/main/java/com/Gongdae9/domain/Bookmark.java
  server/src/main/java/com/Gongdae9/domain/JoinRoom.java
  server/src/main/java/com/Gongdae9/domain/Message.java
  server/src/main/java/com/Gongdae9/domain/Room.java
  server/src/main/java/com/Gongdae9/domain/User.java
Labels: Domain, enhancement

#25 feat: add friend domain
  server/src/main/java/com/Gongdae9/domain/Friend.java
  server/src/main/java/com/Gongdae9/domain/User.java
Labels: Domain, enhancement

#33 Feat/issue 32/create friend
  client/app/src/main/res/layout/activity_main.xml
  server/build.gradle
  server/src/main/java/com/Gongdae9/domain/Friend.java
  server/src/main/java/com/Gongdae9/domain/User.java
  server/src/main/java/com/Gongdae9/friend/api/FriendApiController.java
  server/src/main/java/com/Gongdae9/friend/dto/FriendDto.java
  server/src/main/java/com/Gongdae9/friend/repository/FriendRepository.java
  server/src/main/java/com/Gongdae9/friend/service/FriendService.java
  server/src/main/java/com/Gongdae9/user/api/UserApiController.java
  server/src/main/java/com/Gongdae9/user/dto/CreateUserRequest.java
  server/src/main/java/com/Gongdae9/user/dto/UserDto.java
  server/src/main/java/com/Gongdae9/user/repository/UserRepository.java
  server/src/main/java/com/Gongdae9/user/service/UserService.java
  server/src/main/resources/application.yml
Labels: Spring, enhancement

#36 feat:delete freind
  server/src/main/java/com/Gongdae9/friend/api/FriendApiController.java
  server/src/main/java/com/Gongdae9/friend/repository/FriendRepository.java
  server/src/main/java/com/Gongdae9/friend/service/FriendService.java
Labels: Spring, enhancement

#38 Feature_issue 35_login signup
  server/src/main/java/com/Gongdae9/friend/api/FriendApiController.java
  server/src/main/java/com/Gongdae9/user/api/UserApiController.java
  server/src/main/java/com/Gongdae9/user/dto/LoginRequestDto.java
  server/src/main/java/com/Gongdae9/user/dto/SignupRequestDto.java
  server/src/main/java/com/Gongdae9/user/service/UserService.java
  server/src/test/java/com/Gongdae9/loginSessionTest.java
Labels: Spring, enhancement

#39 feat:create chatRoom
  server/src/main/java/com/Gongdae9/domain/Friend.java
  server/src/main/java/com/Gongdae9/domain/JoinRoom.java
  server/src/main/java/com/Gongdae9/domain/Room.java
  server/src/main/java/com/Gongdae9/friend/api/FriendApiController.java
  server/src/main/java/com/Gongdae9/friend/repository/FriendRepository.java
  server/src/main/java/com/Gongdae9/joinroom/api/JoinRoomApiController.java
  server/src/main/java/com/Gongdae9/joinroom/repository/JoinRoomRepository.java
  server/src/main/java/com/Gongdae9/joinroom/service/JoinRoomService.java
  server/src/main/java/com/Gongdae9/room/repository/RoomRepository.java
  server/src/main/java/com/Gongdae9/room/service/RoomService.java
Labels: Spring, enhancement

#40 Feature UI issue22 profile and setting
  client/app/src/main/res/drawable-v24/back.png
  client/app/src/main/res/drawable-v24/btn_back.png
  client/app/src/main/res/drawable-v24/corner_radius_red.xml
  client/app/src/main/res/layout/activity_pass_change.xml
  client/app/src/main/res/layout/fragment_list.xml
  client/app/src/main/res/layout/fragment_setting.xml
  client/app/src/main/res/layout/fragment_upperbar.xml
  client/app/src/main/res/layout/widget_bar_title_back.xml
  client/app/src/main/res/layout/widget_title_bar_basic.xml
  client/app/src/main/res/values/colors.xml
Labels: Android, xml

#41 refactor: package refacor
  server/src/main/java/com/Gongdae9/bookmark/domain/Bookmark.java
  server/src/main/java/com/Gongdae9/friend/api/FriendApiController.java
  server/src/main/java/com/Gongdae9/friend/domain/Friend.java
  server/src/main/java/com/Gongdae9/friend/dto/FriendDto.java
  server/src/main/java/com/Gongdae9/friend/repository/FriendRepository.java
  server/src/main/java/com/Gongdae9/friend/service/FriendService.java
  server/src/main/java/com/Gongdae9/joinroom/domain/JoinRoom.java
  server/src/main/java/com/Gongdae9/joinroom/repository/JoinRoomRepository.java
  server/src/main/java/com/Gongdae9/joinroom/service/JoinRoomService.java
  server/src/main/java/com/Gongdae9/message/domain/Message.java
  server/src/main/java/com/Gongdae9/room/domain/Room.java
  server/src/main/java/com/Gongdae9/room/repository/RoomRepository.java
  server/src/main/java/com/Gongdae9/room/service/RoomService.java
  server/src/main/java/com/Gongdae9/user/api/UserApiController.java
  server/src/main/java/com/Gongdae9/user/domain/User.java
  server/src/main/java/com/Gongdae9/user/dto/UserDto.java
  server/src/main/java/com/Gongdae9/user/repository/UserRepository.java
  server/src/main/java/com/Gongdae9/user/service/UserService.java
  server/src/test/java/com/Gongdae9/loginSessionTest.java
Labels: Establish

#43 Feature issue28 add user crud
  client/app/src/androidTest/java/com/example/chattingapp/repository/UserRepositoryTest.kt
  client/app/src/androidTest/java/com/example/chattingapp/service/UserServiceTest.kt
  client/app/src/main/java/com/example/chattingapp/dto/User.kt
  client/app/src/main/java/com/example/chattingapp/repository/UserRepository.kt
  client/app/src/main/java/com/example/chattingapp/service/ServiceCallback.kt
  client/app/src/main/java/com/example/chattingapp/service/UserService.kt
  client/app/src/main/res/layout/activity_main.xml
Labels: Android, enhancement

#48 Feature issue47 chatting room
  client/app/src/main/AndroidManifest.xml
  client/app/src/main/java/com/example/chattingapp/dto/ChatMessage.kt
  client/app/src/main/java/com/example/chattingapp/model/ChatMessage.kt
  client/app/src/main/java/com/example/chattingapp/view/MainActivity.kt
  client/app/src/main/java/com/example/chattingapp/view/MessageChatActivity.kt
  client/app/src/main/res/drawable/chat_camera.png
  client/app/src/main/res/drawable/chat_picture.png
  client/app/src/main/res/drawable/corner_radius_chat_company.xml
  client/app/src/main/res/drawable/corner_radius_chat_customer.xml
  client/app/src/main/res/drawable/corner_radius_chatbox.xml
  client/app/src/main/res/drawable/msg_send.png
  client/app/src/main/res/drawable/plus_b.png
  client/app/src/main/res/drawable/sample_pro.png
  client/app/src/main/res/layout/activity_message_chat.xml
  client/app/src/main/res/layout/widget_chat_company.xml
  client/app/src/main/res/layout/widget_chat_customer.xml
  client/app/src/main/res/layout/widget_chat_date.xml
  client/app/src/main/res/mipmap-mdpi/knu_mark.jpg
  client/app/src/main/res/values/colors.xml
Labels: Android, Kotlin, xml

#52 Feature issue28 add room, user, friend api to android
  client/app/build.gradle
  client/app/src/androidTest/java/com/example/chattingapp/service/FriendApiTest.kt
  client/app/src/androidTest/java/com/example/chattingapp/service/RoomApiTest.kt
  client/app/src/androidTest/java/com/example/chattingapp/service/ServiceTestUtils.kt
  client/app/src/androidTest/java/com/example/chattingapp/service/UserApiTest.kt
  client/app/src/androidTest/java/com/example/chattingapp/service/UserServiceTest.kt
  client/app/src/main/java/com/example/chattingapp/dto/Friend.kt
  client/app/src/main/java/com/example/chattingapp/service/RestApiService.kt
  client/app/src/main/java/com/example/chattingapp/service/UserService.kt
  client/app/src/main/java/com/example/chattingapp/util/client/RestServiceGenerator.kt
Labels: Android, enhancement

#57 Feature issue28 rest api wrapping and add runtime exception when status code is not 200
  client/app/src/androidTest/java/com/example/chattingapp/service/FriendApiTest.kt
  client/app/src/androidTest/java/com/example/chattingapp/service/RoomApiTest.kt
  client/app/src/androidTest/java/com/example/chattingapp/service/ServiceTestUtils.kt
  client/app/src/androidTest/java/com/example/chattingapp/service/UserApiTest.kt
  client/app/src/androidTest/java/com/example/chattingapp/util/client/MyStompClientTest.kt
  client/app/src/main/java/com/example/chattingapp/service/FriendApiService.kt
  client/app/src/main/java/com/example/chattingapp/service/RoomApiService.kt
  client/app/src/main/java/com/example/chattingapp/service/ServiceCallback.kt
  client/app/src/main/java/com/example/chattingapp/service/UserApiService.kt
  client/app/src/main/java/com/example/chattingapp/service/util/rest/RestApiService.kt
  client/app/src/main/java/com/example/chattingapp/service/util/rest/RestApiServiceCallback.kt
  client/app/src/main/java/com/example/chattingapp/service/util/rest/RestApiServiceGenerator.kt
  client/app/src/main/java/com/example/chattingapp/service/util/stomp/MyStompClient.kt
Labels: Android, enhancement

#60 [feature-android] : wrapping stomp protocol api
  client/app/build.gradle
  client/app/src/androidTest/java/com/example/chattingapp/service/FriendApiTest.kt
  client/app/src/androidTest/java/com/example/chattingapp/service/MessageApiTest.kt
  client/app/src/androidTest/java/com/example/chattingapp/service/RoomApiTest.kt
  client/app/src/androidTest/java/com/example/chattingapp/service/UserApiTest.kt
  client/app/src/androidTest/java/com/example/chattingapp/util/client/MyStompClientTest.kt
  client/app/src/main/java/com/example/chattingapp/service/ChatMessageApiService.kt
  client/app/src/main/java/com/example/chattingapp/service/FriendApiService.kt
  client/app/src/main/java/com/example/chattingapp/service/RoomApiService.kt
  client/app/src/main/java/com/example/chattingapp/service/UserApiService.kt
  client/app/src/main/java/com/example/chattingapp/service/util/stomp/StompApiService.kt
Labels: Android, enhancement

#63 fix : sync login xml and server
  client/app/src/main/AndroidManifest.xml
  client/app/src/main/java/com/example/chattingapp/view/IntroActivity.kt
  client/app/src/main/java/com/example/chattingapp/view/LoginActivity.kt
Labels: Android, Kotlin, enhancement, xml

#62 [feature-android-ui] : chat room ui
  client/app/src/main/java/com/example/chattingapp/adapter/ChatlistAdapter.kt
  client/app/src/main/java/com/example/chattingapp/adapter/MessagelistAdapter.kt
  client/app/src/main/java/com/example/chattingapp/dto/ChatMessage.kt
  client/app/src/main/java/com/example/chattingapp/dto/User.kt
  client/app/src/main/java/com/example/chattingapp/model/ChatRoom.kt
  client/app/src/main/java/com/example/chattingapp/service/ChatMessageApiService.kt
  client/app/src/main/java/com/example/chattingapp/service/util/stomp/StompApiService.kt
  client/app/src/main/java/com/example/chattingapp/view/MainActivity.kt
  client/app/src/main/java/com/example/chattingapp/view/MessageChatActivity.kt
  client/app/src/main/java/com/example/chattingapp/view/fragment/ChatlistFragment.kt
  client/app/src/main/java/com/example/chattingapp/view/fragment/MessagelistFragment.kt
  client/app/src/main/res/layout/activity_message_chat.xml
  client/app/src/main/res/layout/fragment_messagelist.xml
  client/app/src/main/res/values/strings.xml
Labels: Android, enhancement, xml

#70 [feature-android] : now can send/receive chat message in chat activity
  client/app/src/main/java/com/example/chattingapp/adapter/MessagelistAdapter.kt
  client/app/src/main/java/com/example/chattingapp/view/MessageChatActivity.kt
  client/app/src/main/java/com/example/chattingapp/view/fragment/MessagelistFragment.kt
Labels: Android, enhancement

#66 Feat/issue-65/Invite Friend
  server/src/main/java/com/Gongdae9/friend/service/FriendService.java
  server/src/main/java/com/Gongdae9/joinroom/api/JoinRoomApiController.java
  server/src/main/java/com/Gongdae9/joinroom/service/JoinRoomService.java
Labels: Spring, enhancement

#75 ãfix : get friendlist available
  client/app/src/androidTest/java/com/example/chattingapp/service/FriendApiTest.kt
  client/app/src/androidTest/java/com/example/chattingapp/service/RoomApiTest.kt
  client/app/src/androidTest/java/com/example/chattingapp/service/UserApiTest.kt
  client/app/src/main/java/com/example/chattingapp/adapter/ChatlistAdapter.kt
  client/app/src/main/java/com/example/chattingapp/adapter/FriendlistAdapter.kt
  client/app/src/main/java/com/example/chattingapp/dto/ChatRoom.kt
  client/app/src/main/java/com/example/chattingapp/dto/Friend.kt
  client/app/src/main/java/com/example/chattingapp/model/ChatMessage.kt
  client/app/src/main/java/com/example/chattingapp/model/ChatRoom.kt
  client/app/src/main/java/com/example/chattingapp/model/User.kt
  client/app/src/main/java/com/example/chattingapp/view/IntroActivity.kt
  client/app/src/main/java/com/example/chattingapp/view/MainActivity.kt
  client/app/src/main/java/com/example/chattingapp/view/MessageChatActivity.kt
  client/app/src/main/java/com/example/chattingapp/view/fragment/ChatlistFragment.kt
  client/app/src/main/java/com/example/chattingapp/view/fragment/FriendlistFragment.kt
  client/app/src/main/java/com/example/chattingapp/view/fragment/UserlistFragment.kt
  client/app/src/main/res/layout/fragment_userlist.xml
Labels: Android, Kotlin, xml

#73 feat/issue-71/spring profile
  server/build.gradle
  server/src/main/resources/application.yml
Labels: Establish, Spring

#77 feat/issue-65/invite
  server/src/main/java/com/Gongdae9/room/domain/Room.java
  server/src/main/java/com/Gongdae9/room/repository/RoomRepository.java
  server/src/main/java/com/Gongdae9/room/service/RoomService.java
Labels: Spring, enhancement

#82 feat: add RoomDto to get chatroom list
  server/src/main/java/com/Gongdae9/room/dto/RoomDto.java
  server/src/main/java/com/Gongdae9/room/service/RoomService.java
  server/src/main/java/com/Gongdae9/user/api/UserApiController.java
Labels: Spring, enhancement

#90 feat: add spring logback
  server/.gitignore
  server/logs/local/pc-web.log
  server/src/main/java/com/Gongdae9/DemoApplication.java
  server/src/main/resources/logback-spring.xml
Labels: Establish, Spring, enhancement

#91 feat:add MessasgeDto
  server/src/main/java/com/Gongdae9/message/controller/MessageController.java
  server/src/main/java/com/Gongdae9/message/domain/EventSubDto.java
  server/src/main/java/com/Gongdae9/message/domain/Message.java
  server/src/main/java/com/Gongdae9/message/domain/MessageDto.java
  server/src/main/java/com/Gongdae9/message/service/MessageService.java
Labels: Spring, enhancement

#93 fix: handle lazy initialization error
  server/src/main/java/com/Gongdae9/message/controller/MessageController.java
  server/src/main/java/com/Gongdae9/message/service/MessageService.java
Labels: Spring, bug

#92 feat: add checking all users in a chatting room
  server/logs/local/pc-web.log
  server/src/main/java/com/Gongdae9/room/api/RoomApiContoller.java
  server/src/main/java/com/Gongdae9/room/dto/ChattingUserDto.java
  server/src/main/java/com/Gongdae9/user/api/UserApiController.java
Labels: Spring, enhancement

#99 Establish/issue 11/stomp client
  server/src/main/java/com/Gongdae9/message/controller/MessageController.java
Labels: Spring, bug

#94 fix: add transactional annotation to resolve lazyInitializationException
  server/src/main/java/com/Gongdae9/message/service/MessageService.java
Labels: Spring, bug

#101 feat: add return room api
  server/src/main/java/com/Gongdae9/room/api/RoomApiContoller.java
  server/src/main/java/com/Gongdae9/room/service/RoomService.java
Labels: Spring, enhancement
